package com.qiu.pojo;

public class canteen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.canteen_name
     *
     * @mbggenerated
     */
    private String canteenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.id
     *
     * @return the value of canteen.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.id
     *
     * @param id the value for canteen.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.canteen_name
     *
     * @return the value of canteen.canteen_name
     *
     * @mbggenerated
     */
    public String getCanteenName() {
        return canteenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.canteen_name
     *
     * @param canteenName the value for canteen.canteen_name
     *
     * @mbggenerated
     */
    public void setCanteenName(String canteenName) {
        this.canteenName = canteenName == null ? null : canteenName.trim();
    }
}