package com.qiu.pojo;

public class dishes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.window
     *
     * @mbggenerated
     */
    private Integer window;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.material
     *
     * @mbggenerated
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.cookingTime
     *
     * @mbggenerated
     */
    private Integer cookingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.remainder
     *
     * @mbggenerated
     */
    private Integer remainder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishes.picUrl
     *
     * @mbggenerated
     */
    private String picurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.id
     *
     * @return the value of dishes.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.id
     *
     * @param id the value for dishes.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.name
     *
     * @return the value of dishes.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.name
     *
     * @param name the value for dishes.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.window
     *
     * @return the value of dishes.window
     *
     * @mbggenerated
     */
    public Integer getWindow() {
        return window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.window
     *
     * @param window the value for dishes.window
     *
     * @mbggenerated
     */
    public void setWindow(Integer window) {
        this.window = window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.material
     *
     * @return the value of dishes.material
     *
     * @mbggenerated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.material
     *
     * @param material the value for dishes.material
     *
     * @mbggenerated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.cookingTime
     *
     * @return the value of dishes.cookingTime
     *
     * @mbggenerated
     */
    public Integer getCookingtime() {
        return cookingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.cookingTime
     *
     * @param cookingtime the value for dishes.cookingTime
     *
     * @mbggenerated
     */
    public void setCookingtime(Integer cookingtime) {
        this.cookingtime = cookingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.remainder
     *
     * @return the value of dishes.remainder
     *
     * @mbggenerated
     */
    public Integer getRemainder() {
        return remainder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.remainder
     *
     * @param remainder the value for dishes.remainder
     *
     * @mbggenerated
     */
    public void setRemainder(Integer remainder) {
        this.remainder = remainder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishes.picUrl
     *
     * @return the value of dishes.picUrl
     *
     * @mbggenerated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishes.picUrl
     *
     * @param picurl the value for dishes.picUrl
     *
     * @mbggenerated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }
}