package com.qiu.pojo;

public class favorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.window
     *
     * @mbggenerated
     */
    private Integer window;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.material
     *
     * @mbggenerated
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.cookingTime
     *
     * @mbggenerated
     */
    private Integer cookingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.name
     *
     * @return the value of favorite.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.name
     *
     * @param name the value for favorite.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.window
     *
     * @return the value of favorite.window
     *
     * @mbggenerated
     */
    public Integer getWindow() {
        return window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.window
     *
     * @param window the value for favorite.window
     *
     * @mbggenerated
     */
    public void setWindow(Integer window) {
        this.window = window;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.material
     *
     * @return the value of favorite.material
     *
     * @mbggenerated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.material
     *
     * @param material the value for favorite.material
     *
     * @mbggenerated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.cookingTime
     *
     * @return the value of favorite.cookingTime
     *
     * @mbggenerated
     */
    public Integer getCookingtime() {
        return cookingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.cookingTime
     *
     * @param cookingtime the value for favorite.cookingTime
     *
     * @mbggenerated
     */
    public void setCookingtime(Integer cookingtime) {
        this.cookingtime = cookingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.user
     *
     * @return the value of favorite.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.user
     *
     * @param user the value for favorite.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }
}