package com.qiu.pojo;

import java.util.Date;

public class orderHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderhistory.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderhistory.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderhistory.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderhistory.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderhistory.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderhistory.id
     *
     * @return the value of orderhistory.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderhistory.id
     *
     * @param id the value for orderhistory.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderhistory.num
     *
     * @return the value of orderhistory.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderhistory.num
     *
     * @param num the value for orderhistory.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderhistory.date
     *
     * @return the value of orderhistory.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderhistory.date
     *
     * @param date the value for orderhistory.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderhistory.status
     *
     * @return the value of orderhistory.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderhistory.status
     *
     * @param status the value for orderhistory.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderhistory.user
     *
     * @return the value of orderhistory.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderhistory.user
     *
     * @param user the value for orderhistory.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }
}