package com.qiu.pojo;

public class orderTemporary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertemporary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertemporary.dish
     *
     * @mbggenerated
     */
    private String dish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertemporary.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertemporary.belong
     *
     * @mbggenerated
     */
    private Integer belong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertemporary.id
     *
     * @return the value of ordertemporary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertemporary.id
     *
     * @param id the value for ordertemporary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertemporary.dish
     *
     * @return the value of ordertemporary.dish
     *
     * @mbggenerated
     */
    public String getDish() {
        return dish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertemporary.dish
     *
     * @param dish the value for ordertemporary.dish
     *
     * @mbggenerated
     */
    public void setDish(String dish) {
        this.dish = dish == null ? null : dish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertemporary.price
     *
     * @return the value of ordertemporary.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertemporary.price
     *
     * @param price the value for ordertemporary.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertemporary.belong
     *
     * @return the value of ordertemporary.belong
     *
     * @mbggenerated
     */
    public Integer getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertemporary.belong
     *
     * @param belong the value for ordertemporary.belong
     *
     * @mbggenerated
     */
    public void setBelong(Integer belong) {
        this.belong = belong;
    }
}