package com.qiu.pojo;

import java.util.Date;

public class user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.schoolNum
     *
     * @mbggenerated
     */
    private String schoolnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastDate
     *
     * @mbggenerated
     */
    private Date lastdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.schoolNum
     *
     * @return the value of user.schoolNum
     *
     * @mbggenerated
     */
    public String getSchoolnum() {
        return schoolnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.schoolNum
     *
     * @param schoolnum the value for user.schoolNum
     *
     * @mbggenerated
     */
    public void setSchoolnum(String schoolnum) {
        this.schoolnum = schoolnum == null ? null : schoolnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastDate
     *
     * @return the value of user.lastDate
     *
     * @mbggenerated
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastDate
     *
     * @param lastdate the value for user.lastDate
     *
     * @mbggenerated
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }
}