package com.qiu.pojo;

public class windows {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column windows.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column windows.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column windows.cateen
     *
     * @mbggenerated
     */
    private Integer cateen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column windows.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column windows.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column windows.id
     *
     * @return the value of windows.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column windows.id
     *
     * @param id the value for windows.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column windows.name
     *
     * @return the value of windows.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column windows.name
     *
     * @param name the value for windows.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column windows.cateen
     *
     * @return the value of windows.cateen
     *
     * @mbggenerated
     */
    public Integer getCateen() {
        return cateen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column windows.cateen
     *
     * @param cateen the value for windows.cateen
     *
     * @mbggenerated
     */
    public void setCateen(Integer cateen) {
        this.cateen = cateen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column windows.num
     *
     * @return the value of windows.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column windows.num
     *
     * @param num the value for windows.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column windows.location
     *
     * @return the value of windows.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column windows.location
     *
     * @param location the value for windows.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}