package com.qiu.dao;

import com.qiu.pojo.canteen;
import com.qiu.pojo.canteenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface canteenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int countByExample(canteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int deleteByExample(canteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int insert(canteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int insertSelective(canteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    List<canteen> selectByExample(canteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    canteen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") canteen record, @Param("example") canteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") canteen record, @Param("example") canteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(canteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(canteen record);
}