package com.qiu.dao;

import com.qiu.pojo.dishes;
import com.qiu.pojo.dishesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface dishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int countByExample(dishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int deleteByExample(dishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int insert(dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int insertSelective(dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    List<dishes> selectByExample(dishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    dishes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") dishes record, @Param("example") dishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") dishes record, @Param("example") dishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(dishes record);
}