package com.qiu.dao;

import com.qiu.pojo.favorite;
import com.qiu.pojo.favoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface favoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int countByExample(favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int deleteByExample(favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int insert(favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int insertSelective(favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    List<favorite> selectByExample(favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    favorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") favorite record, @Param("example") favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") favorite record, @Param("example") favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(favorite record);
}