package com.qiu.dao;

import com.qiu.pojo.orderHistory;
import com.qiu.pojo.orderHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface orderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int countByExample(orderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int deleteByExample(orderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int insert(orderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int insertSelective(orderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    List<orderHistory> selectByExample(orderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    orderHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") orderHistory record, @Param("example") orderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") orderHistory record, @Param("example") orderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(orderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderhistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(orderHistory record);
}