package com.qiu.dao;

import com.qiu.pojo.windows;
import com.qiu.pojo.windowsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface windowsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int countByExample(windowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int deleteByExample(windowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int insert(windows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int insertSelective(windows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    List<windows> selectByExample(windowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    windows selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") windows record, @Param("example") windowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") windows record, @Param("example") windowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(windows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table windows
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(windows record);
}